name: React Vite deployment on S3

on:
  push:
    branches:
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm i

    - name: Build Vite App
      run: npm run build

    - name: Deploy Frontend
      uses: jakejarvis/s3-sync-action@master
      with: 
        args: --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET}}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: 'dist'

    - name: Jest test
      run : npm run test

    - name: Cypress tests
      uses: cypress-io/github-action@v4
      with:
        start: npm run dev
        wait-on: 'http://localhost:5173'
        browser: chrome
      env:
        VITE_MIAPI: ${{ secrets.VITE_MIAPI }}
        VITE_NAME: ${{ secrets.VITE_NAME }}
        VITE_PASSWORD: ${{ secrets.VITE_PASSWORD }}
